env:
  ARCH: amd64

task:
  matrix:
    - name: 13.0-RELEASE
      freebsd_instance:
        image_family: freebsd-13-0
    - name: 13.0-STABLE
      freebsd_instance:
        image_family: freebsd-13-0-snap
    - name: 12.2-STABLE
      freebsd_instance:
        image_family: freebsd-12-2-snap
    - name: 12.2-RELEASE
      freebsd_instance:
        image_family: freebsd-12-2
    - name: 11.4-RELEASE
      freebsd_instance:
        image_family: freebsd-11-4
  env:
    DO: distcheck
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y autoconf automake atf lutok pkgconf sqlite3
  script:
    - ./admin/travis-build.sh
